import { ImageResponse } from "next/og";

import { loadOgFonts } from "@/lib/og/fonts";
import {
  COLORS,
  CirclesGlyph,
  Coin,
  FONT_DISPLAY,
  FONT_MONO,
  Frame,
  Kicker,
  OG_SIZE,
} from "@/lib/og/shared";

// Generated by Satori; node runtime keeps it consistent with the app's other
// routes and avoids edge-bundling the font reads.
export const runtime = "nodejs";

// This card never changes, so cache it hard once rendered.
const CACHE = "public, max-age=31536000, immutable";

// The static landing embed — what renders when the app's main URL is cast.
export async function GET() {
  const fonts = await loadOgFonts();

  return new ImageResponse(
    (
      <Frame>
        {/* masthead */}
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
          }}
        >
          <Kicker>Circles</Kicker>
          <Kicker>Gas-free · One tap</Kicker>
        </div>

        {/* headline + coin */}
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            gap: 48,
          }}
        >
          <div
            style={{
              display: "flex",
              flexDirection: "column",
              fontFamily: FONT_DISPLAY,
              fontWeight: 800,
              fontSize: 112,
              lineHeight: 0.92,
              letterSpacing: -3,
              textTransform: "uppercase",
              color: COLORS.ink,
            }}
          >
            <span style={{ display: "flex" }}>Money</span>
            <span style={{ display: "flex", alignItems: "center", gap: 16 }}>
              <span style={{ display: "flex" }}>That</span>
              <span
                style={{
                  display: "flex",
                  background: COLORS.sun,
                  padding: "0 14px 8px",
                }}
              >
                Grows
              </span>
            </span>
            <span style={{ display: "flex" }}>On You.</span>
          </div>

          <Coin size={300}>
            <CirclesGlyph size={184} />
          </Coin>
        </div>

        {/* tagline */}
        <div style={{ display: "flex" }}>
          <span
            style={{
              fontFamily: FONT_MONO,
              fontWeight: 700,
              fontSize: 30,
              color: COLORS.inkSoft,
            }}
          >
            Personal currency for humans. Set up gas-free, in one tap.
          </span>
        </div>
      </Frame>
    ),
    { ...OG_SIZE, fonts, headers: { "Cache-Control": CACHE } },
  );
}
